Rails.application.routes.draw do
  get 'parser/ypmd'
  root to: 'application#index'
  get 'create_task', to: 'application#create_task', as: 'create_task'
  post 'task_create', to: 'tasks#create', as: 'task_create'
  get 'task/[:task_id]', to: 'tasks#view', as: 'task_view'
  get 'database_numbers', to: 'application#database', as: 'database_numbers'
  get 'send_sms', to: 'application#send_sms', as: 'send_sms'
  post 'start_send_sms', to: 'sms#send_sms', as: 'start_send_sms'
  get 'parsing', to: 'application#parsing', as: 'parsing'
  get 'statistics', to: 'application#statistics', as: 'statistics'
  get 'sim_cards', to: 'application#sim_cards', as: 'sim_cards'
  post 'sim_cards/add_card', to: 'sim_cards#add_card', as: 'add_sim_card'
  post 'sim_cards/add_funds', to: 'sim_cards#add_funds', as: 'add_funds'
  get 'sim_cards/add_funds/[:id]', to: 'sim_cards#view_deposit_history', as: 'view_deposit_history'

  # Parsing

  # 999.md

  # Transport
  get '999md/transport_all', to: 'parser999md#parse_all_transport', as: 'transport_all_999'
  get '999md/passengers_cars', to: 'parser999md#cars_passengers', as: 'passengers_cars_999'
  get '999md/parts_for_cars', to: 'parser999md#parts_for_cars', as: 'parts_for_cars_999'
  get '999md/supplies_and_accessories', to: 'parser999md#supplies_and_accessories', as: 'supplies_and_accessories_999'
  get '999md/special_equipment_and_tools', to: 'parser999md#special_equipment_and_tools', as: 'special_equipment_and_tools_999'
  get '999md/auto_glass_and_optics', to: 'parser999md#auto_glass_and_optics', as: 'auto_glass_and_optics_999'
  get '999md/parts_for_trucks', to: 'parser999md#parts_for_trucks', as: 'parts_for_trucks_999'
  get '999md/wheel_and_tires', to: 'parser999md#wheel_and_tires', as: 'wheel_and_tires_999'
  get '999md/trailers', to: 'parser999md#trailers', as: 'trailers_999'
  get '999md/agriculture', to: 'parser999md#agriculture', as: 'agriculture_999'
  get '999md/special_equipment', to: 'parser999md#special_equipment', as: 'special_equipment_999'
  get '999md/snowmobiles_and_jet_ski', to: 'parser999md#snowmobiles_and_jet_ski', as: 'snowmobiles_and_jet_ski_999'
  get '999md/airplanes', to: 'parser999md#airplanes', as: 'airplanes_999'
  get '999md/buses_and_minibuses', to: 'parser999md#buses_and_minibuses', as: 'buses_and_minibuses_999'
  get '999md/trucks', to: 'parser999md#trucks', as: 'trucks_999'
  get '999md/motorcycles', to: 'parser999md#motorcycles', as: 'motorcycles_999'
  get '999md/spare_parts_for_motorcycles', to: 'parser999md#spare_parts_for_motorcycles', as: 'spare_parts_for_motorcycles_999'
  get '999md/moto_equipment', to: 'parser999md#moto_equipment', as: 'moto_equipment_999'
  get '999md/electric_scooters', to: 'parser999md#electric_scooters', as: 'electric_scooters_999'
  get '999md/gps_navigation', to: 'parser999md#gps_navigation', as: 'gps_navigation_999'
  get '999md/carcaraudio', to: 'parser999md#carcaraudio', as: 'carcaraudio_999'
  get '999md/acoustic', to: 'parser999md#acoustic', as: 'acoustic_999'
  get '999md/supplies_of_car_audio', to: 'parser999md#supplies_of_car_audio', as: 'supplies_of_car_audio_999'
  get '999md/video_recorders', to: 'parser999md#video_recorders', as: 'video_recorders_999'
  get '999md/radars_alarms', to: 'parser999md#radars_alarms', as: 'radars_alarms_999'
  get '999md/bicycles', to: 'parser999md#bicycles', as: 'bicycles_999'
  get '999md/bike_gear', to: 'parser999md#bike_gear', as: 'bike_gear_999'
  get '999md/spare_parts_for_bicycles', to: 'parser999md#spare_parts_for_bicycles', as: 'spare_parts_for_bicycles_999'
  get '999md/cargo', to: 'parser999md#cargo', as: 'cargo_999'
  get '999md/auto_service', to: 'parser999md#auto_service', as: 'auto_service_999'
  get '999md/rent_a_car', to: 'parser999md#rent_a_car', as: 'rent_a_car_999'
  get '999md/passenger', to: 'parser999md#passenger', as: 'passenger_999'
  get '999md/transport_miscellaneous', to: 'parser999md#transport_miscellaneous', as: 'transport_miscellaneous_999'

  # Computers and Equipment
  get '999md/parse_computers_all', to: 'parser999md#parse_computers_all', as: 'parse_computers_all_999'
  get '999md/laptops', to: 'parser999md#laptops', as: 'laptops_999'
  get '999md/desktops', to: 'parser999md#desktops', as: 'desktops_999'
  get '999md/game_console', to: 'parser999md#game_console', as: 'game_console_999'
  get '999md/tablets', to: 'parser999md#tablets', as: 'tablets_999'
  get '999md/pc_accessories', to: 'parser999md#pc_accessories', as: 'pc_accessories_999'
  get '999md/printers', to: 'parser999md#printers', as: 'printers_999'
  get '999md/copiers_multifunction', to: 'parser999md#copiers_multifunction', as: 'copiers_multifunction_999'
  get '999md/consumables', to: 'parser999md#consumables', as: 'consumables_999'
  get '999md/office_equipment', to: 'parser999md#office_equipment', as: 'office_equipment999'
  get '999md/calculators_notepads', to: 'parser999md#calculators_notepads', as: 'calculators_notepads_999'
  get '999md/scanners', to: 'parser999md#scanners', as: 'scanners_999'
  get '999md/software', to: 'parser999md#software', as: 'software_999'
  get '999md/computer_services', to: 'parser999md#computer_services', as: 'computer_services_999'
  get '999md/computers_miscellaneous', to: 'parser999md#computers_miscellaneous', as: 'computers_miscellaneous_999'
  get '999md/monitors', to: 'parser999md#monitors', as: 'monitors_999'
  get '999md/accessories_laptops', to: 'parser999md#accessories_laptops', as: 'accessories_laptops_999'
  get '999md/hdd_ssd', to: 'parser999md#hdd_ssd', as: 'hdd_ssd_999'
  get '999md/pc_video_cards', to: 'parser999md#pc_video_cards', as: 'pc_video_cards_999'
  get '999md/pc_audio_multimedia', to: 'parser999md#pc_audio_multimedia', as: 'pc_audio_multimedia_999'
  get '999md/pc_memory', to: 'parser999md#pc_memory', as: 'pc_memory_999'
  get '999md/pc_keyboards_mice_joysticks', to: 'parser999md#pc_keyboards_mice_joysticks', as: 'pc_keyboards_mice_joysticks_999'
  get '999md/pc_networking', to: 'parser999md#pc_networking', as: 'pc_networking_999'
  get '999md/pc_motherboards', to: 'parser999md#pc_motherboards', as: 'pc_motherboards_999'
  get '999md/pc_processors', to: 'parser999md#pc_processors', as: 'pc_processors_999'
  get '999md/cases_powersupplies_ups', to: 'parser999md#cases_powersupplies_ups', as: 'cases_powersupplies_ups_999'
  get '999md/usb_flash', to: 'parser999md#usb_flash', as: 'usb_flash_999'
  get '999md/cd_dvd_rom', to: 'parser999md#cd_dvd_rom', as: 'cd_dvd_rom_999'
  get '999md/pc_coolers', to: 'parser999md#pc_coolers', as: 'pc_coolers_999'
  get '999md/usb_pcmcia_firewire_infrared', to: 'parser999md#usb_pcmcia_firewire_infrared', as: 'usb_pcmcia_firewire_infrared_999'
  get '999md/pc_controllers_adapters', to: 'parser999md#pc_controllers_adapters', as: 'pc_controllers_adapters_999'
  get '999md/pc_cd_dvds', to: 'parser999md#pc_cd_dvds', as: 'pc_cd_dvds_999'
  get '999md/radio_components', to: 'parser999md#radio_components', as: 'radio_components_999'
  get '999md/storage_fdd_mo_zip_streamers', to: 'parser999md#storage_fdd_mo_zip_streamers', as: 'storage_fdd_mo_zip_streamers_999'

  # Construction and Repair
  get '999md/construction_repair_all_parse', to: 'parser999md#construction_repair_all_parse', as: 'construction_repair_all_parse_999'
  get '999md/facing_materials_finishing', to: 'parser999md#facing_materials_finishing', as: 'facing_materials_finishing_999'
  get '999md/roofing_materials_999', to: 'parser999md#roofing_materials', as: 'roofing_materials_999'
  get '999md/insulating_materials_999', to: 'parser999md#insulating_materials', as: 'insulating_materials_999'
  get '999md/lumber', to: 'parser999md#lumber', as: 'lumber_999'
  get '999md/building_materials', to: 'parser999md#building_materials', as: 'building_materials_999'
  get '999md/construction_electrical', to: 'parser999md#construction_electrical', as: 'construction_electrical_999'
  get '999md/construct_pumps_pump', to: 'parser999md#construct_pumps_pump', as: 'construct_pumps_pump_999'
  get '999md/construction_equipment', to: 'parser999md#construction_equipment', as: 'construction_equipment_999'
  get '999md/construct_gas_powered', to: 'parser999md#construct_gas_powered', as: 'construct_gas_powered_999'
  get '999md/lighting_construction', to: 'parser999md#lighting_construction', as: 'lighting_construction_999'
  get '999md/construction_pneumatics', to: 'parser999md#construction_pneumatics', as: 'construction_pneumatics_999'
  get '999md/construct_hand_tool', to: 'parser999md#construct_hand_tool', as: 'construct_hand_tool_999'
  get '999md/plumbing_bath_construct', to: 'parser999md#plumbing_bath_construct', as: 'plumbing_bath_construct_999'
  get '999md/construct_pipes', to: 'parser999md#construct_pipes', as: 'construct_pipes_999'
  get '999md/construct_sinks', to: 'parser999md#construct_sinks', as: 'construct_sinks_999'
  get '999md/taps_construct', to: 'parser999md#taps_construct', as: 'taps_construct_999'
  get '999md/construction_miscellaneous', to: 'parser999md#construction_miscellaneous', as: 'construction_miscellaneous_999'
  get '999md/construction_metal', to: 'parser999md#construction_metal', as: 'construction_metal_999'
  get '999md/construct_articles_of_concrete', to: 'parser999md#construct_articles_of_concrete', as: 'construct_articles_of_concrete_999'
  get '999md/construct_wood', to: 'parser999md#construct_wood', as: 'construct_wood_999'
  get '999md/glass_construct', to: 'parser999md#glass_construct', as: 'glass_construct_999'
  get '999md/construct_heating', to: 'parser999md#construct_heating', as: 'construct_heating_999'
  get '999md/construct_windows_doors', to: 'parser999md#construct_windows_doors', as: 'construct_windows_doors_999'
  get '999md/repairs_construct', to: 'parser999md#repairs_construct', as: 'repairs_construct_999'
  get '999md/construction_work', to: 'parser999md#construction_work', as: 'construction_work_999'
  get '999md/plumbing_works_construct', to: 'parser999md#plumbing_works_construct', as: 'plumbing_works_construct_999'
  get '999md/electrical_work_construct', to: 'parser999md#electrical_work_construct', as: 'electrical_work_construct_999'
  get '999md/design_and_architecture_construct', to: 'parser999md#design_and_architecture_construct', as: 'design_and_architecture_construct_999'
  get '999md/metal_work_construct', to: 'parser999md#metal_work_construct', as: 'metal_work_construct_999'

  # Business
  get '999md/business_parse_all', to: 'parser999md#business_parse_all', as: 'business_parse_all_999'
  get '999md/current_business', to: 'parser999md#current_business', as: 'current_business_999'
  get '999md/sites_and_developing', to: 'parser999md#sites_and_developing', as: 'sites_and_developing_999'
  get '999md/doing_business', to: 'parser999md#doing_business', as: 'doing_business_999'
  get '999md/shares_in', to: 'parser999md#shares_in', as: 'shares_in_999'
  get '999md/tenders_auctions', to: 'parser999md#tenders_auctions', as: 'tenders_auctions_999'
  get '999md/miscellaneous_business', to: 'parser999md#miscellaneous_business', as: 'miscellaneous_business_999'
  get '999md/cash_registers_scales', to: 'parser999md#cash_registers_scales', as: 'cash_registers_scales_999'
  get '999md/legal_services', to: 'parser999md#legal_services', as: 'legal_services_999'
  get '999md/advertising_services', to: 'parser999md#advertising_services', as: 'advertising_services_999'
  get '999md/leasing', to: 'parser999md#leasing', as: 'leasing_999'
  get '999md/printing_design', to: 'parser999md#printing_design', as: 'printing_design_999'
  get '999md/accounting_audit_services', to: 'parser999md#accounting_audit_services', as: 'accounting_audit_services_999'
  get '999md/insurance_services_consulting', to: 'parser999md#insurance_services_consulting', as: 'insurance_services_consulting_999'

  # Real Estate
  get '999md/real_estate_all', to: 'parser999md#real_estate_all', as: 'real_estate_all_999'
  get '999md/appartaments_and_rooms', to: 'parser999md#appartaments_and_rooms', as: 'appartaments_and_rooms_999'
  get '999md/houses_and_garden', to: 'parser999md#houses_and_garden', as: 'houses_and_garden_999'
  get '999md/lands', to: 'parser999md#lands', as: 'lands_999'
  get '999md/commercial_real_estate', to: 'parser999md#commercial_real_estate', as: 'commercial_real_estate_999'
  get '999md/garages_and_parking', to: 'parser999md#garages_and_parking', as: 'garages_and_parking_999'
  get '999md/real_estate_miscellaneous', to: 'parser999md#real_estate_miscellaneous', as: 'real_estate_miscellaneous_999'
  get '999md/real_estate_services', to: 'parser999md#real_estate_services', as: 'real_estate_services_999'

  # Phones
  get '999md/parse_phones_all', to: 'parser999md#parse_phones_all', as: 'parse_phones_all_999'
  get '999md/mobile_phones', to: 'parser999md#mobile_phones', as: 'mobile_phones_999'
  get '999md/mobile_phones_accessories', to: 'parser999md#mobile_phones_accessories', as: 'mobile_phones_accessories_999'
  get '999md/mobile_phones_parts', to: 'parser999md#mobile_phones_parts', as: 'mobile_phones_parts_999'
  get '999md/mobile_numbers', to: 'parser999md#mobile_numbers', as: 'mobile_numbers_999'
  get '999md/mobile_service', to: 'parser999md#mobile_service', as: 'mobile_service_999'
  get '999md/home_phones', to: 'parser999md#home_phones', as: 'home_phones_999'
  get '999md/radio', to: 'parser999md#radio', as: 'radio_999'
  get '999md/pbx', to: 'parser999md#pbx', as: 'pbx_999'
  get '999md/fax', to: 'parser999md#fax', as: 'fax_999'
  get '999md/mobile_chargers', to: 'parser999md#mobile_chargers', as: 'mobile_chargers_999'
  get '999md/phones_miscellaneous', to: 'parser999md#phones_miscellaneous', as: 'phones_miscellaneous_999'

  # Clothes
  get '999md/parse_all_clothes', to: 'parser999md#parse_all_clothes', as: 'parse_all_clothes_999'
  get '999md/woman_clothes', to: 'parser999md#woman_clothes', as: 'woman_clothes_999'
  get '999md/woman_shoes', to: 'parser999md#woman_shoes', as: 'woman_shoes_999'
  get '999md/female_underwear', to: 'parser999md#female_underwear', as: 'female_underwear_999'
  get '999md/man_clothes', to: 'parser999md#man_clothes', as: 'man_clothes_999'
  get '999md/man_shoes', to: 'parser999md#man_shoes', as: 'man_shoes_999'
  get '999md/sport_shoes', to: 'parser999md#sport_shoes', as: 'sport_shoes_999'
  get '999md/sport_clothes', to: 'parser999md#sport_clothes', as: 'sport_clothes_999'
  get '999md/thermal_underwear', to: 'parser999md#thermal_underwear', as: 'thermal_underwear_999'
  get '999md/wedding_clothes', to: 'parser999md#wedding_clothes', as: 'wedding_clothes_999'
  get '999md/wedding_shoes', to: 'parser999md#wedding_shoes', as: 'wedding_shoes_999'
  get '999md/wedding_accessories', to: 'parser999md#wedding_accessories', as: 'wedding_accessories_999'
  get '999md/special_clothing', to: 'parser999md#special_clothing', as: 'special_clothing_999'
  get '999md/carnival_costumes', to: 'parser999md#carnival_costumes', as: 'carnival_costumes_999'
  get '999md/clothes_miscellaneous', to: 'parser999md#clothes_miscellaneous', as: 'clothes_miscellaneous_999'
  get '999md/clothing_for_children', to: 'parser999md#clothing_for_children', as: 'clothing_for_children_999'
  get '999md/childrens_shoes', to: 'parser999md#childrens_shoes', as: 'childrens_shoes_999'
  get '999md/delivery_clothes', to: 'parser999md#delivery_clothes', as: 'delivery_clothes_999'
  get '999md/laundry', to: 'parser999md#laundry', as: 'laundry_999'
  get '999md/watches', to: 'parser999md#watches', as: 'watches_999'
  get '999md/jewelry', to: 'parser999md#jewelry', as: 'jewelry_999'
  get '999md/glasses', to: 'parser999md#glasses', as: 'glasses_999'
  get '999md/bags_briefcases', to: 'parser999md#bags_briefcases', as: 'bags_briefcases_999'
  get '999md/belts_gloves', to: 'parser999md#belts_gloves', as: 'belts_gloves_999'
  get '999md/neckties_shawls', to: 'parser999md#neckties_shawls', as: 'neckties_shawls_999'
  get '999md/hats', to: 'parser999md#hats', as: 'hats_999'

  # Furniture and Interior
  get '999md/furniture_all_parse', to: 'parser999md#furniture_all_parse', as: 'furniture_all_parse_999'
  get '999md/upholstery_furniture', to: 'parser999md#upholstery_furniture', as: 'upholstery_furniture_999'
  get '999md/bedrooms', to: 'parser999md#bedrooms', as: 'bedrooms_999'
  get '999md/tables_chairs_stools', to: 'parser999md#tables_chairs_stools', as: 'tables_chairs_stools_999'
  get '999md/cabinets_cabinets_coupe', to: 'parser999md#cabinets_cabinets_coupe', as: 'cabinets_cabinets_coupe_999'
  get '999md/kitchen', to: 'parser999md#kitchen', as: 'kitchen_999'
  get '999md/antiques', to: 'parser999md#antiques', as: 'antiques_999'
  get '999md/outdoor_furniture', to: 'parser999md#outdoor_furniture', as: 'outdoor_furniture_999'
  get '999md/furniture_for_horeca', to: 'parser999md#furniture_for_horeca', as: 'furniture_for_horeca_999'
  get '999md/inflatable_furniture', to: 'parser999md#inflatable_furniture', as: 'inflatable_furniture_999'
  get '999md/custom_furniture', to: 'parser999md#custom_furniture', as: 'custom_furniture_999'
  get '999md/pictures_watches_interior', to: 'parser999md#pictures_watches_interior', as: 'pictures_watches_interior_999'
  get '999md/blinds_curtains', to: 'parser999md#blinds_curtains', as: 'blinds_curtains_999'
  get '999md/home_mirrors', to: 'parser999md#home_mirrors', as: 'home_mirrors_999'

  # Audio Video Photo
  get '999md/audio_video_photo_parse_all', to: 'parser999md#audio_video_photo_parse_all', as: 'audio_video_photo_parse_all_999'
  get '999md/tv', to: 'parser999md#tv', as: 'tv_999'
  get '999md/video_camera', to: 'parser999md#video_camera', as: 'video_camera_999'
  get '999md/dvd_cd_players', to: 'parser999md#dvd_cd_players', as: 'dvd_cd_players_999'
  get '999md/satellite_dish', to: 'parser999md#satellite_dish', as: 'satellite_dish_999'
  get '999md/tv_projectors', to: 'parser999md#tv_projectors', as: 'tv_projectors_999'
  get '999md/digital_cameras', to: 'parser999md#digital_cameras', as: 'digital_cameras_999'
  get '999md/lenses_cvetofiltry', to: 'parser999md#lenses_cvetofiltry', as: 'lenses_cvetofiltry_999'
  get '999md/accessories_photo', to: 'parser999md#accessories_photo', as: 'accessories_photo_999'
  get '999md/photo_flash_light', to: 'parser999md#photo_flash_light', as: 'photo_flash_light_999'
  get '999md/tripods_monopods', to: 'parser999md#tripods_monopods', as: 'tripods_monopods_999'
  get '999md/binoculars_telescopes_microscopes', to: 'parser999md#binoculars_telescopes_microscopes', as: 'binoculars_telescopes_microscopes_999'
  get '999md/photo_memory_cards', to: 'parser999md#photo_memory_cards', as: 'photo_memory_cards_999'
  get '999md/photos_bags_cases', to: 'parser999md#photos_bags_cases', as: 'photos_bags_cases_999'
  get '999md/accums_photo', to: 'parser999md#accums_photo', as: 'accums_photo_999'
  get '999md/miscellaneous_audiovideophoto', to: 'parser999md#miscellaneous_audiovideophoto', as: 'miscellaneous_audiovideophoto_999'
  get '999md/acoustics_columns', to: 'parser999md#acoustics_columns', as: 'acoustics_columns_999'
  get '999md/microphones_audiovideophoto', to: 'parser999md#microphones_audiovideophoto', as: 'microphones_audiovideophoto_999'
  get '999md/portable_audio', to: 'parser999md#portable_audio', as: 'portable_audio_999'
  get '999md/home_audio', to: 'parser999md#home_audio', as: 'home_audio_999'
  get '999md/stereo_components', to: 'parser999md#stereo_components', as: 'stereo_components_999'
  get '999md/home_cinema', to: 'parser999md#home_cinema', as: 'home_cinema_999'
  get '999md/accessories_video', to: 'parser999md#accessories_video', as: 'accessories_video_999'
  get '999md/audio_studio', to: 'parser999md#audio_studio', as: 'audio_studio_999'
  get '999md/studio_lighting', to: 'parser999md#studio_lighting', as: 'studio_lighting_999'
  get '999md/accessories_studio', to: 'parser999md#accessories_studio', as: 'accessories_studio_999'
  get '999md/studio_video', to: 'parser999md#studio_video', as: 'studio_video_999'
  get '999md/digitization', to: 'parser999md#digitization', as: 'digitization_999'
  get '999md/audiovideophoto_repair', to: 'parser999md#audiovideophoto_repair', as: 'audiovideophoto_repair_999'

  # All Else
  get '999md/all_else_parse_all', to: 'parser999md#all_else_parse_all', as: 'all_else_parse_all_999'
  get '999md/all_else_professional_equipment', to: 'parser999md#all_else_professional_equipment', as: 'all_else_professional_equipment_999'
  get '999md/industry_raw_materials', to: 'parser999md#industry_raw_materials', as: 'industry_raw_materials_999'
  get '999md/security_safety', to: 'parser999md#security_safety', as: 'security_safety_999'
  get '999md/lombard', to: 'parser999md#lombard', as: 'lombard_999'
  get '999md/handmade', to: 'parser999md#handmade', as: 'handmade_999'
  get '999md/food_drinks_tobacco', to: 'parser999md#food_drinks_tobacco', as: 'food_drinks_tobacco_999'
  get '999md/reports_dissertations', to: 'parser999md#reports_dissertations', as: 'reports_dissertations_999'
  get '999md/sex_shops', to: 'parser999md#sex_shops', as: 'sex_shops_999'
  get '999md/books_periodicals', to: 'parser999md#books_periodicals', as: 'books_periodicals_999'
  get '999md/translation', to: 'parser999md#translation', as: 'translation_999'
  get '999md/lost_found', to: 'parser999md#lost_found', as: 'lost_found_999'
  get '999md/sewing', to: 'parser999md#sewing', as: 'sewing_999'
  get '999md/all_else_miscellaneous', to: 'parser999md#all_else_miscellaneous', as: 'all_else_miscellaneous_999'

  # All For Celebrations
  get '999md/allforcelebrations_parse_all', to: 'parser999md#allforcelebrations_parse_all', as: 'allforcelebrations_parse_all_999'
  get '999md/little_touches', to: 'parser999md#little_touches', as: 'little_touches_999'
  get '999md/fans_of_smoking', to: 'parser999md#fans_of_smoking', as: 'fans_of_smoking_999'
  get '999md/fireworks_sky_lanterns', to: 'parser999md#fireworks_sky_lanterns', as: 'fireworks_sky_lanterns_999'
  get '999md/elite_alcohol', to: 'parser999md#elite_alcohol', as: 'elite_alcohol_999'
  get '999md/flowers', to: 'parser999md#flowers', as: 'flowers_999'
  get '999md/photo_video_services', to: 'parser999md#photo_video_services', as: 'photo_video_services_999'
  get '999md/musicians', to: 'parser999md#musicians', as: 'musicians_999'
  get '999md/maintenance_celebrations', to: 'parser999md#maintenance_celebrations', as: 'maintenance_celebrations_999'
  get '999md/transport_for_celebrations', to: 'parser999md#transport_for_celebrations', as: 'transport_for_celebrations_999'
  get '999md/cookery', to: 'parser999md#cookery', as: 'cookery_999'
  get '999md/allForCelebrations_miscellaneous', to: 'parser999md#allForCelebrations_miscellaneous', as: 'allForCelebrations_miscellaneous_999'

  # Household Appliances
  get '999md/household_appliances_parse_all', to: 'parser999md#household_appliances_parse_all', as: 'household_appliances_parse_all_999'
  get '999md/washingMachines', to: 'parser999md#washingMachines', as: 'washingMachines_999'
  get '999md/refrigerators', to: 'parser999md#refrigerators', as: 'refrigerators_999'
  get '999md/stove_oven', to: 'parser999md#stove_oven', as: 'stove_oven_999'
  get '999md/microwaves', to: 'parser999md#microwaves', as: 'microwaves_999'
  get '999md/dishwashers', to: 'parser999md#dishwashers', as: 'dishwashers_999'
  get '999md/hoods', to: 'parser999md#hoods', as: 'hoods_999'
  get '999md/kitchen_appliances', to: 'parser999md#kitchen_appliances', as: 'kitchen_appliances_999'
  get '999md/tehnika_dlya_doma', to: 'parser999md#tehnika_dlya_doma', as: 'tehnika_dlya_doma_999'
  get '999md/personal_care', to: 'parser999md#personal_care', as: 'personal_care_999'
  get '999md/air_conditioners', to: 'parser999md#air_conditioners', as: 'air_conditioners_999'
  get '999md/boilersBoilers', to: 'parser999md#boilersBoilers', as: 'boilersBoilers_999'
  get '999md/air_cleaners_humidifiers', to: 'parser999md#air_cleaners_humidifiers', as: 'air_cleaners_humidifiers_999'
  get '999md/appliance_repair', to: 'parser999md#appliance_repair', as: 'appliance_repair_999'
  get '999md/household_miscellaneous', to: 'parser999md#household_miscellaneous', as: 'household_miscellaneous_999'

  # Sports Health Beauty
  get '999md/sports_health_beauty_all', to: 'parser999md#sports_health_beauty_all', as: 'sports_health_beauty_all_999'
  get '999md/trainers_equipment', to: 'parser999md#trainers_equipment', as: 'trainers_equipment_999'
  get '999md/nutrition', to: 'parser999md#nutrition', as: 'nutrition_999'
  get '999md/sports_clubs', to: 'parser999md#sports_clubs', as: 'sports_clubs_999'
  get '999md/pools', to: 'parser999md#pools', as: 'pools_999'
  get '999md/scooters_skates_skis', to: 'parser999md#scooters_skates_skis', as: 'scooters_skates_skis_999'
  get '999md/medical_facilities', to: 'parser999md#medical_facilities', as: 'medical_facilities_999'
  get '999md/drugs_medicines', to: 'parser999md#drugs_medicines', as: 'drugs_medicines_999'
  get '999md/essential_oils_teas_herbs', to: 'parser999md#essential_oils_teas_herbs', as: 'essential_oils_teas_herbs_999'
  get '999md/nails_manicure_pedicure', to: 'parser999md#nails_manicure_pedicure', as: 'nails_manicure_pedicure_999'
  get '999md/beauty_makeup', to: 'parser999md#beauty_makeup', as: 'beauty_makeup_999'
  get '999md/hair_care', to: 'parser999md#hair_care', as: 'hair_care_999'
  get '999md/traditional_medicine', to: 'parser999md#traditional_medicine', as: 'traditional_medicine_999'
  get '999md/perfumes_cosmetics', to: 'parser999md#perfumes_cosmetics', as: 'perfumes_cosmetics_999'
  get '999md/care_beautry', to: 'parser999md#care_beautry', as: 'care_beautry_999'
  get '999md/sport_health_beauty_miscellaneous', to: 'parser999md#sport_health_beauty_miscellaneous', as: 'sport_health_beauty_miscellaneous_999'

  # Tourism Leisure
  get '999md/tourism_leisure_parse_all', to: 'parser999md#tourism_leisure_parse_all', as: 'tourism_leisure_parse_all_999'
  get '999md/holidays_abroad', to: 'parser999md#holidays_abroad', as: 'holidays_abroad_999'
  get '999md/tourism_moldova', to: 'parser999md#tourism_moldova', as: 'tourism_moldova_999'
  get '999md/tents', to: 'parser999md#tents', as: 'tents_999'
  get '999md/leisure_products', to: 'parser999md#leisure_products', as: 'leisure_products_999'
  get '999md/flashlights', to: 'parser999md#flashlights', as: 'flashlights_999'
  get '999md/backpacks_bags', to: 'parser999md#backpacks_bags', as: 'backpacks_bags_999'
  get '999md/sauna', to: 'parser999md#sauna', as: 'sauna_999'
  get '999md/massage', to: 'parser999md#massage', as: 'massage_999'
  get '999md/entertainment_recreation', to: 'parser999md#entertainment_recreation', as: 'entertainment_recreation_999'
  get '999md/guns_knives', to: 'parser999md#guns_knives', as: 'guns_knives_999'
  get '999md/fishing_rods_tackles', to: 'parser999md#fishing_rods_tackles', as: 'fishing_rods_tackles_999'
  get '999md/tourism_miscellaneous', to: 'parser999md#tourism_miscellaneous', as: 'tourism_miscellaneous_999'

  # All for home and office
  get '999md/all_for_home_office_parse_all', to: 'parser999md#all_for_home_office_parse_all', as: 'all_for_home_office_parse_all_999'
  get '999md/cookware_dishes', to: 'parser999md#cookware_dishes', as: 'cookware_dishes_999'
  get '999md/fabrics_linen', to: 'parser999md#fabrics_linen', as: 'fabrics_linen_999'
  get '999md/household_supplies', to: 'parser999md#household_supplies', as: 'household_supplies_999'
  get '999md/household_chemistry', to: 'parser999md#household_chemistry', as: 'household_chemistry_999'
  get '999md/accessories_toilet', to: 'parser999md#accessories_toilet', as: 'accessories_toilet_999'
  get '999md/stationary', to: 'parser999md#stationary', as: 'stationary_999'
  get '999md/safes_fireproof_cabinets', to: 'parser999md#safes_fireproof_cabinets', as: 'safes_fireproof_cabinets_999'
  get '999md/presentation_equipment', to: 'parser999md#presentation_equipment', as: 'presentation_equipment_999'
  get '999md/miscellaneous_allforhomeoffice', to: 'parser999md#miscellaneous_allforhomeoffice', as: 'miscellaneous_allforhomeoffice_999'
  get '999md/cleaning_services', to: 'parser999md#cleaning_services', as: 'cleaning_services_999'

  # Children World
  get '999md/children_world_parse_all', to: 'parser999md#children_world_parse_all', as: 'children_world_parse_all_999'
  get '999md/stroller', to: 'parser999md#stroller', as: 'stroller_999'
  get '999md/toys', to: 'parser999md#toys', as: 'toys_999'
  get '999md/furniture_children', to: 'parser999md#furniture_children', as: 'furniture_children_999'
  get '999md/walkers_slings_cots', to: 'parser999md#walkers_slings_cots', as: 'walkers_slings_cots_999'
  get '999md/care_hygiene_children', to: 'parser999md#care_hygiene_children', as: 'care_hygiene_children_999'
  get '999md/car_chair_children', to: 'parser999md#car_chair_children', as: 'car_chair_children_999'
  get '999md/power_accessories_food_children', to: 'parser999md#power_accessories_food_children', as: 'power_accessories_food_children_999'
  get '999md/children_miscellaneous', to: 'parser999md#children_miscellaneous', as: 'children_miscellaneous_999'
  get '999md/education_child_care', to: 'parser999md#education_child_care', as: 'education_child_care_999'

  # Agriculture
  get '999md/agriculture_parse_all', to: 'parser999md#agriculture_parse_all', as: 'agriculture_parse_all_999'
  get '999md/livestock', to: 'parser999md#livestock', as: 'livestock_999'
  get '999md/aviculture', to: 'parser999md#aviculture', as: 'aviculture_999'
  get '999md/beekeeping_honey', to: 'parser999md#beekeeping_honey', as: 'beekeeping_honey_999'
  get '999md/animal_feed', to: 'parser999md#animal_feed', as: 'animal_feed_999'
  get '999md/pisciculture', to: 'parser999md#pisciculture', as: 'pisciculture_999'
  get '999md/fertilizers_chemicals', to: 'parser999md#fertilizers_chemicals', as: 'fertilizers_chemicals_999'
  get '999md/seeds_seedlings', to: 'parser999md#seeds_seedlings', as: 'seeds_seedlings_999'
  get '999md/farm_equipment', to: 'parser999md#farm_equipment', as: 'farm_equipment_999'
  get '999md/wood_coal_fuel', to: 'parser999md#wood_coal_fuel', as: 'wood_coal_fuel_999'
  get '999md/agro_tools', to: 'parser999md#agro_tools', as: 'agro_tools_999'
  get '999md/agro_other', to: 'parser999md#agro_other', as: 'agro_other_999'
  get '999md/berries_mushrooms', to: 'parser999md#berries_mushrooms', as: 'berries_mushrooms_999'
  get '999md/dried_fruits', to: 'parser999md#dried_fruits', as: 'dried_fruits_999'
  get '999md/vegetables_fruits', to: 'parser999md#vegetables_fruits', as: 'vegetables_fruits_999'
  get '999md/dairy_products', to: 'parser999md#dairy_products', as: 'dairy_products_999'
  get '999md/grain_cereals_flours', to: 'parser999md#grain_cereals_flours', as: 'grain_cereals_flours_999'
  get '999md/agro_oil', to: 'parser999md#agro_oil', as: 'agro_oil_999'
  get '999md/nuts', to: 'parser999md#nuts', as: 'nuts_999'
  get '999md/eggs', to: 'parser999md#eggs', as: 'eggs_999'
  get '999md/meat_bird_fish', to: 'parser999md#meat_bird_fish', as: 'meat_bird_fish_999'
  get '999md/agro_services', to: 'parser999md#agro_services', as: 'agro_services_999'

  # Animals and Plants
  get '999md/animals_plants_parse_all', to: 'parser999md#animals_plants_parse_all', as: 'animals_plants_parse_all_999'
  get '999md/dogs', to: 'parser999md#dogs', as: 'dogs_999'
  get '999md/cats', to: 'parser999md#cats', as: 'cats_999'
  get '999md/the_birds', to: 'parser999md#the_birds', as: 'the_birds_999'
  get '999md/fish', to: 'parser999md#fish', as: 'fish_999'
  get '999md/other_animals', to: 'parser999md#other_animals', as: 'other_animals_999'
  get '999md/accessories_for_animals', to: 'parser999md#accessories_for_animals', as: 'accessories_for_animals_999'
  get '999md/animals_missing', to: 'parser999md#animals_missing', as: 'animals_missing_999'
  get '999md/tying_animals', to: 'parser999md#tying_animals', as: 'tying_animals_999'
  get '999md/care_animals', to: 'parser999md#care_animals', as: 'care_animals_999'
  get '999md/plants_flowers', to: 'parser999md#plants_flowers', as: 'plants_flowers_999'
  get '999md/inventory_plants', to: 'parser999md#inventory_plants', as: 'inventory_plants_999'
  get '999md/miscellaneous_animals_plants', to: 'parser999md#miscellaneous_animals_plants', as: 'miscellaneous_animals_plants_999'

  # Musical Instruments
  get '999md/music_instruments_parse_all', to: 'parser999md#music_instruments_parse_all', as: 'music_instruments_parse_all_999'
  get '999md/guitars', to: 'parser999md#guitars', as: 'guitars_999'
  get '999md/guitar_effects', to: 'parser999md#guitar_effects', as: 'guitar_effects_999'
  get '999md/keyboard_instruments', to: 'parser999md#keyboard_instruments', as: 'keyboard_instruments_999'
  get '999md/accordions', to: 'parser999md#accordions', as: 'accordions_999'
  get '999md/strings', to: 'parser999md#strings', as: 'strings_999'
  get '999md/winds', to: 'parser999md#winds', as: 'winds_999'
  get '999md/percussion', to: 'parser999md#percussion', as: 'percussion_999'
  get '999md/speakers_acoustics', to: 'parser999md#speakers_acoustics', as: 'speakers_acoustics_999'
  get '999md/audio_mixers', to: 'parser999md#audio_mixers', as: 'audio_mixers_999'
  get '999md/amplifiers', to: 'parser999md#amplifiers', as: 'amplifiers_999'
  get '999md/stage_equipment', to: 'parser999md#stage_equipment', as: 'stage_equipment_999'
  get '999md/dj_equipment', to: 'parser999md#dj_equipment', as: 'dj_equipment_999'
  get '999md/accessories_components', to: 'parser999md#accessories_components', as: 'accessories_components_999'
  get '999md/racks_frames_chairs', to: 'parser999md#racks_frames_chairs', as: 'racks_frames_chairs_999'
  get '999md/cases_music', to: 'parser999md#cases_music', as: 'cases_music_999'
  get '999md/repair_music', to: 'parser999md#repair_music', as: 'repair_music_999'
  get '999md/learning_music', to: 'parser999md#learning_music', as: 'learning_music_999'
  get '999md/recording_mixing', to: 'parser999md#recording_mixing', as: 'recording_mixing_999'
  get '999md/rent_music', to: 'parser999md#rent_music', as: 'rent_music_999'
  get '999md/miscellaneous_music', to: 'parser999md#miscellaneous_music', as: 'miscellaneous_music_999'

  # Profi.md

  get 'profimd/parser', to: 'profimd#parser', as: 'profimd_parser'

  # yellowpages.md

  # Companies

  get 'ypmd/parse_companies', to: 'parserypmd#parser', as: 'parse_companies_ypmd'

  # for xls files

  get 'energy_import', to: 'csv#energy_import'
  get 'wellness_import', to: 'csv#wellness_import'
  get 'doza_import', to: 'csv#doza_import'
  get 'ghidtur_import', to: 'csv#ghidtur_import'

end
